### PR TITLE
feat: Updated docker to work with new mariner Azure image

### PR DESCRIPTION
**Pull request by dploeger**

### CODE REVIEW

**Review by ThomasMinor — APPROVED** [review]
And why is this needed?

**Comment by dploeger** [comment]
> And why is this needed?

Because: https://github.com/dodevops/azure-advanced-backup/actions/runs/12186550669/job/33995311040#step:5:161

**Comment by ThomasMinor** [comment]
Ahh, I see -> https://github.com/Azure/azure-cli/issues/29827

**Review by timdeluxe — APPROVED** [review]
Thanks 🎁

**Pull request merged**
